name: uni_chat_sdk
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #* Localizations
  # flutter_localizations:
  #   sdk: flutter
  easy_localization: ^3.0.7

  # Firebase
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.16

  # State Management
  flutter_riverpod: ^2.5.1

  # UI
  google_fonts: ^6.2.1
  flutter_chat_bubble: ^2.0.2
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  chewie: ^1.8.1
  video_player: ^2.9.1
  cached_network_image: ^3.3.1
  audio_waveforms: ^1.2.0
  bot_toast: ^4.1.3

  # Utils
  uuid: ^4.4.0

  # Storage
  flutter_cache_manager: ^3.3.2

  # Media Picker
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  timeago: ^3.6.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
